JOINT_NAMES = {
    'pelvis': 0,
    'left_hip': 16,
    'right_hip': 11,
    'spine1': 1,
    'left_knee': 17,
    'right_knee': 12,
    'spine2': 2,
    'left_ankle': 18,
    'right_ankle': 13,
    'left_foot': 19,
    'right_foot': 14,
    'left_foot_end': 20,
    'right_foot_end': 15,
    'neck': 3,
    'head': 4,
    'left_shoulder': 8,
    'right_shoulder': 5,
    'left_elbow': 9,
    'right_elbow': 6,
    'left_wrist': 10,
    'right_wrist': 7,
}
